name: "Entangled Check"
description: "Verify tangled output files are in sync with markdown sources"
branding:
  icon: "check-circle"
  color: "blue"

inputs:
  version:
    description: "Version of entangled to install (e.g. 'v0.1.0', 'latest')"
    required: false
    default: "latest"
  args:
    description: "Additional arguments to pass to entangled tangle --dry-run"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Determine version
      id: version
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          echo "tag=$(gh release view --json tagName -q .tagName)" >> "$GITHUB_OUTPUT"
        else
          echo "tag=${{ inputs.version }}" >> "$GITHUB_OUTPUT"
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Determine platform
      id: platform
      shell: bash
      run: |
        case "$RUNNER_OS-$RUNNER_ARCH" in
          Linux-X64)   echo "target=x86_64-unknown-linux-gnu" >> "$GITHUB_OUTPUT"; echo "ext=tar.gz" >> "$GITHUB_OUTPUT" ;;
          Linux-ARM64) echo "target=aarch64-unknown-linux-gnu" >> "$GITHUB_OUTPUT"; echo "ext=tar.gz" >> "$GITHUB_OUTPUT" ;;
          macOS-X64)   echo "target=x86_64-apple-darwin" >> "$GITHUB_OUTPUT"; echo "ext=tar.gz" >> "$GITHUB_OUTPUT" ;;
          macOS-ARM64) echo "target=aarch64-apple-darwin" >> "$GITHUB_OUTPUT"; echo "ext=tar.gz" >> "$GITHUB_OUTPUT" ;;
          Windows-X64) echo "target=x86_64-pc-windows-msvc" >> "$GITHUB_OUTPUT"; echo "ext=zip" >> "$GITHUB_OUTPUT" ;;
          *) echo "::error::Unsupported platform: $RUNNER_OS-$RUNNER_ARCH"; exit 1 ;;
        esac

    - name: Download entangled
      shell: bash
      run: |
        TAG="${{ steps.version.outputs.tag }}"
        TARGET="${{ steps.platform.outputs.target }}"
        EXT="${{ steps.platform.outputs.ext }}"
        ARCHIVE="entangled-${TAG}-${TARGET}.${EXT}"
        gh release download "$TAG" --repo entangled/entangled-rs --pattern "$ARCHIVE"
        if [ "$EXT" = "tar.gz" ]; then
          tar xzf "$ARCHIVE"
          chmod +x entangled
          echo "$PWD" >> "$GITHUB_PATH"
        else
          unzip "$ARCHIVE"
          echo "$PWD" >> "$GITHUB_PATH"
        fi
      env:
        GH_TOKEN: ${{ github.token }}

    - name: Check tangled files
      shell: bash
      run: entangled tangle --dry-run ${{ inputs.args }}
