//! Weave command implementation.
//!
//! Renders literate markdown documents to human-readable output. HTML, markdown,
//! and Quarto (`.qmd`) targets are produced natively; every other target is
//! generated by piping clean markdown through `pandoc` (which must be on PATH or
//! specified with `--pandoc`).

use std::io::Write;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

use entangled::errors::{EntangledError, Result};
use entangled::interface::Context;
use entangled::{weave_document, HtmlOptions};

/// Selected weave backend / output family.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Backend {
    /// Native self-contained HTML.
    Html,
    /// Native clean markdown, written with the given file extension.
    Markdown { ext: &'static str },
    /// Delegated to pandoc, targeting the given pandoc writer with the given
    /// output file extension.
    Pandoc { format: String, ext: String },
}

/// Options for the weave command.
#[derive(Debug, Clone)]
pub struct WeaveOptions {
    /// Output target: `html`, `markdown`, `quarto`, or any pandoc format.
    pub to: String,
    /// Explicit output path (only valid with a single input; `-` means stdout
    /// for native text targets).
    pub output: Option<PathBuf>,
    /// Emit an HTML fragment instead of a standalone document.
    pub fragment: bool,
    /// Path to the pandoc executable.
    pub pandoc: String,
    /// Glob patterns to filter source files.
    pub glob: Vec<String>,
    /// Specific files to weave (empty means all source files).
    pub files: Vec<PathBuf>,
    /// Suppress normal output.
    pub quiet: bool,
}

impl Default for WeaveOptions {
    fn default() -> Self {
        Self {
            to: "html".to_string(),
            output: None,
            fragment: false,
            pandoc: "pandoc".to_string(),
            glob: Vec::new(),
            files: Vec::new(),
            quiet: false,
        }
    }
}

/// Executes the weave command.
pub fn weave(ctx: &Context, options: WeaveOptions) -> Result<()> {
    let backend = resolve_backend(&options.to);

    let inputs = select_inputs(ctx, &options)?;
    if inputs.is_empty() {
        return Err(EntangledError::Other(
            "No source files to weave (check source_patterns or the given files)".to_string(),
        ));
    }

    let to_stdout = options.output.as_deref() == Some(Path::new("-"));
    if options.output.is_some() && inputs.len() > 1 {
        return Err(EntangledError::Config(format!(
            "--output requires a single input file, but {} were selected",
            inputs.len()
        )));
    }

    for input in &inputs {
        weave_one(ctx, input, &backend, &options, to_stdout)?;
    }

    Ok(())
}

/// Resolves a `--to` string into a backend.
fn resolve_backend(to: &str) -> Backend {
    match to.to_lowercase().as_str() {
        "html" | "htm" => Backend::Html,
        "markdown" | "md" | "gfm" | "commonmark" => Backend::Markdown { ext: "md" },
        "quarto" | "qmd" => Backend::Markdown { ext: "qmd" },
        other => {
            let ext = match other {
                "latex" => "tex",
                "beamer" | "pdf" => "pdf",
                "revealjs" | "slidy" | "slideous" | "dzslides" | "s5" => "html",
                _ => other,
            };
            Backend::Pandoc {
                format: other.to_string(),
                ext: ext.to_string(),
            }
        }
    }
}

/// Determines which source files to weave.
fn select_inputs(ctx: &Context, options: &WeaveOptions) -> Result<Vec<PathBuf>> {
    let has_filters = !options.files.is_empty() || !options.glob.is_empty();
    if !has_filters {
        return ctx.source_files();
    }
    let mut selected = Vec::new();
    if !options.files.is_empty() {
        selected.extend(ctx.source_files_filtered(&options.files)?);
    }
    if !options.glob.is_empty() {
        selected.extend(ctx.source_files_glob(&options.glob)?);
    }
    selected.sort();
    selected.dedup();
    Ok(selected)
}

/// Weaves a single input file according to the selected backend.
fn weave_one(
    ctx: &Context,
    input: &Path,
    backend: &Backend,
    options: &WeaveOptions,
    to_stdout: bool,
) -> Result<()> {
    let resolved_input = ctx.resolve_path(input);
    let content = std::fs::read_to_string(&resolved_input)?;
    let doc = weave_document(&content, Some(input), &ctx.config)?;

    let out_path =
        |ext: &str| output_path(&resolved_input, options, ext).map(|p| ctx.resolve_path(&p));

    match backend {
        Backend::Html => {
            let html = doc.to_html(&HtmlOptions {
                standalone: !options.fragment,
                title: None,
            });
            emit(&html, out_path("html").as_deref(), to_stdout, options.quiet)
        }
        Backend::Markdown { ext } => {
            let md = doc.to_markdown();
            emit(&md, out_path(ext).as_deref(), to_stdout, options.quiet)
        }
        Backend::Pandoc { format, ext } => {
            let md = doc.to_markdown();
            let out_path = out_path(ext).ok_or_else(|| {
                EntangledError::Config(
                    "pandoc output cannot be written to stdout; provide a file path".to_string(),
                )
            })?;
            run_pandoc(&options.pandoc, format, &md, &out_path)?;
            if !options.quiet {
                println!("weave: {} -> {}", input.display(), out_path.display());
            }
            Ok(())
        }
    }
}

/// Computes the output path for a native target, honoring `--output`.
///
/// Returns `None` when output should go to stdout.
fn output_path(input: &Path, options: &WeaveOptions, ext: &str) -> Option<PathBuf> {
    if let Some(out) = &options.output {
        if out.as_path() == Path::new("-") {
            return None;
        }
        return Some(out.clone());
    }
    let mut candidate = input.with_extension(ext);
    // Avoid overwriting the source file when the extension matches.
    if candidate == input {
        let stem = input
            .file_stem()
            .map(|s| s.to_string_lossy().to_string())
            .unwrap_or_else(|| "output".to_string());
        candidate = input.with_file_name(format!("{}.woven.{}", stem, ext));
    }
    Some(candidate)
}

/// Writes rendered text to a file or stdout.
fn emit(content: &str, path: Option<&Path>, to_stdout: bool, quiet: bool) -> Result<()> {
    match (path, to_stdout) {
        (None, _) | (_, true) => {
            print!("{}", content);
            Ok(())
        }
        (Some(path), false) => {
            if let Some(parent) = path.parent() {
                if !parent.as_os_str().is_empty() {
                    std::fs::create_dir_all(parent)?;
                }
            }
            std::fs::write(path, content)?;
            if !quiet {
                println!("weave: wrote {}", path.display());
            }
            Ok(())
        }
    }
}

/// Pipes markdown through pandoc to produce the requested format.
fn run_pandoc(pandoc: &str, format: &str, markdown: &str, out_path: &Path) -> Result<()> {
    let mut cmd = Command::new(pandoc);
    cmd.arg("-f").arg("markdown");
    // `pdf` is produced via an output-file extension, not a `-t pdf` writer.
    if format != "pdf" {
        cmd.arg("-t").arg(format);
    }
    cmd.arg("-o").arg(out_path);
    cmd.stdin(Stdio::piped());

    let mut child = cmd.spawn().map_err(|e| {
        if e.kind() == std::io::ErrorKind::NotFound {
            EntangledError::Other(format!(
                "pandoc not found (looked for '{}'). Install pandoc or pass --pandoc <path> \
                 (native targets html, markdown, quarto need no pandoc).",
                pandoc
            ))
        } else {
            EntangledError::Io(e)
        }
    })?;

    child
        .stdin
        .take()
        .ok_or_else(|| EntangledError::Other("failed to open pandoc stdin".to_string()))?
        .write_all(markdown.as_bytes())?;

    let status = child.wait()?;
    if !status.success() {
        return Err(EntangledError::Other(format!(
            "pandoc exited with {} while producing {}",
            status, format
        )));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    fn ctx_with(dir: &Path) -> Context {
        Context::default_for_dir(dir.to_path_buf()).unwrap()
    }

    #[test]
    fn resolve_backend_native_and_pandoc() {
        assert_eq!(resolve_backend("html"), Backend::Html);
        assert_eq!(resolve_backend("md"), Backend::Markdown { ext: "md" });
        assert_eq!(resolve_backend("quarto"), Backend::Markdown { ext: "qmd" });
        assert_eq!(
            resolve_backend("latex"),
            Backend::Pandoc {
                format: "latex".to_string(),
                ext: "tex".to_string()
            }
        );
        assert_eq!(
            resolve_backend("pdf"),
            Backend::Pandoc {
                format: "pdf".to_string(),
                ext: "pdf".to_string()
            }
        );
    }

    #[test]
    fn output_path_avoids_overwriting_source() {
        let opts = WeaveOptions::default();
        let p = output_path(Path::new("doc.qmd"), &opts, "qmd").unwrap();
        assert_eq!(p, PathBuf::from("doc.woven.qmd"));

        let p = output_path(Path::new("doc.md"), &opts, "html").unwrap();
        assert_eq!(p, PathBuf::from("doc.html"));
    }

    #[test]
    fn weave_html_writes_sibling_file() {
        let dir = tempdir().unwrap();
        fs::write(
            dir.path().join("doc.md"),
            "# Title\n\n```python #main file=main.py\n<<body>>\n```\n\n```python #body\npass\n```\n",
        )
        .unwrap();
        let ctx = ctx_with(dir.path());

        let opts = WeaveOptions {
            quiet: true,
            ..Default::default()
        };
        weave(&ctx, opts).unwrap();

        let html_path = dir.path().join("doc.html");
        assert!(html_path.exists());
        let html = fs::read_to_string(html_path).unwrap();
        assert!(html.contains("<!DOCTYPE html>"));
        assert!(html.contains("href=\"#block-body\""));
    }

    #[test]
    fn weave_markdown_target_writes_clean_md() {
        let dir = tempdir().unwrap();
        fs::write(
            dir.path().join("doc.md"),
            "# T\n\n```python #main file=main.py\nprint('x')\n```\n",
        )
        .unwrap();
        let ctx = ctx_with(dir.path());

        let opts = WeaveOptions {
            to: "markdown".to_string(),
            quiet: true,
            ..Default::default()
        };
        weave(&ctx, opts).unwrap();

        let out = dir.path().join("doc.md").with_extension("md");
        // Source is doc.md, so the woven output must not clobber it.
        let woven = dir.path().join("doc.woven.md");
        assert!(woven.exists());
        assert_eq!(out, dir.path().join("doc.md"));
        let md = fs::read_to_string(woven).unwrap();
        assert!(!md.contains("#main file=main.py"));
        assert!(md.contains("```python"));
    }

    #[test]
    fn weave_output_flag_rejects_multiple_inputs() {
        let dir = tempdir().unwrap();
        fs::write(dir.path().join("a.md"), "# A\n").unwrap();
        fs::write(dir.path().join("b.md"), "# B\n").unwrap();
        let ctx = ctx_with(dir.path());

        let opts = WeaveOptions {
            output: Some(PathBuf::from("out.html")),
            quiet: true,
            ..Default::default()
        };
        let result = weave(&ctx, opts);
        assert!(result.is_err());
    }

    #[test]
    fn weave_no_sources_errors() {
        let dir = tempdir().unwrap();
        let ctx = ctx_with(dir.path());
        let opts = WeaveOptions {
            quiet: true,
            ..Default::default()
        };
        assert!(weave(&ctx, opts).is_err());
    }
}
